### PR TITLE
External: Fix extending external types with

### PR DESCRIPTION
**Pull request by haraldkl**
There is another issue with external projects, when we try to extend a type that is defined in an external project, we fail for type bound procedures, as they do not get exported, and similarly also for public variables in that type. For variables I don't want to include the documentation in the json serialization. Instead I insert a text with a link to the type we inherit the variable from. This doesn't seem to be proper though, yet. Maybe it needs to go through Markdown processing first? The make_links works however. (The example in the testsuite is updated accordingly to cover this case)

### CODE REVIEW

**Review by ZedThree — APPROVED** [review]
LGTM, thanks @haraldkl!

Let me know when it's ready to merge

**Comment by haraldkl** [comment]
I've added the test for boundprocs. Unfortunately, the link to the extended type doesn't show up in the documentation. Something is still not working quite as it should, I guess.

**Comment by haraldkl** [comment]
Still not sure how I destroyed the link. I moved the stop in the graphs part, but this shouldn't affect the documentation text, I think. Previously it worked. For example in https://geb.inf.tu-dresden.de/doxy/musubi/module/mus_abortcriteria_module.html#type-mus_abortcriteria_type it creates the link to the extended type (in the text and in the graph). Will need to look into that somewhat closer, but I don't know when I'll find time for that.

**Comment by ZedThree** [comment]
I might have some time this week to look into it too

**Comment by ZedThree** [comment]
It looks like the issue is that the type names from the external module aren't getting lowercased around here: https://github.com/Fortran-FOSS-Programmers/ford/blob/cfa3281c377af67129c444faebb0fc01b196d901/ford/sourceform.py#L1180-L1202

so the look-up fails, because we're looking up the lowercased name. I haven't established _why_ yet though.

**Comment by haraldkl** [comment]
I believe it is related to #425, it seems to work now for me in the test_data project. I also had to take care of the generic attribute, and for completeness we'd also need to consider bindings. But I ignored the bindings now, because it looks like when it tries to produce the summary for it, it fails in the renderer, because it passes a string, and doesn't have a 'meta' attribute. I guess, we'd need to pull more doc from the external project into the serialization, which doesn't really make sense in my opinion, as the documentation should remain in the other project. It should be sufficient to follow the link to the extended type.

**Comment by haraldkl** [comment]
Tests failed because I missed updating the assertion after introducing a new entity to link to.

**Comment by haraldkl** [comment]
OK, I hope this is now fine to merge now. It appears to be working to me. Thanks!

**Review by ZedThree — APPROVED** [review]
LGTM, thanks @haraldkl!

**Pull request merged**
