### PR TITLE
Docs: rst fixes for LaTeX syntax

### PR DESCRIPTION
**Pull request by Meax5qiu**
rst renderer displays backslashes literally, better don't escape them.

### CODE REVIEW

**Review by ZedThree — APPROVED** [review]

**Comment by ZedThree** [comment]
Looks great, thanks @Meax5qiu ! You closed this before I could merge it -- is there a problem with it?

**Comment by Meax5qiu** [comment]
Yes, Github was too clever for me, and I messed up with my own fork/PR. Are you still able to merge it, or should I re-create it?

**Comment by Meax5qiu** [comment]
Sorry…

**Comment by ZedThree** [comment]
No worries, looks like reopening it wasn't a problem! I'll let the tests run and then merge it. Thanks again!

**Comment by Meax5qiu** [comment]
Great. Thanks! It seems like friction losses from converting Github wiki syntax to readthedocs rst. Love it btw to have that page at hand!

I just checked: all the other occurrences of `\` in the `docs/` subdirectory are harmless.

**Pull request merged**
