### PR TITLE
fix internal procedure's calls not showing up in call graphs

### PR DESCRIPTION
**Pull request by JosephWood2001**
procedures that are internal to a procedure will now show their calls in call graphs.

### CODE REVIEW

**Comment by ZedThree** [comment]
Does this obey the [`proc_internals`](https://forddocs.readthedocs.io/en/latest/user_guide/project_file_options.html#proc-internals) setting?

**Comment by JosephWood2001** [comment]
Whoops, I didn't try this setting when doing my first commit.

looking into it, when proc_internals was off, the internal calls wouldn't show up in the call graphs 👍 , but the calls made by the internal calls wouldn't show up for the parent of the internal calls either 👎 (both before and after my first commit).

This commit fixes that issue by skipping over nodes that aren't 'visible'

**Comment by ZedThree** [comment]
Thanks @JosephWood2001 ! Please could you add a test or two for this?

**Comment by JosephWood2001** [comment]
👍 , I've also moved where/how the internal proc calls are added to the all calls graph to a more appropriate spot.

**Review by ZedThree — APPROVED** [review]

**Comment by ZedThree** [comment]
Lovely, thanks!

**Pull request merged**
